spring.application.name=DemoProductManagementSystem
server.port=9099
server.servlet.context-path=/api/v1

#jwt config
jwt.secret=dev-secret-please-change-32-bytes!!
# 15 * 60 * 1000 = 15 minutes in milliseconds
jwt.access-token-expiration=900000
# 7 * 24 * 60 * 60 * 1000 = 7 days in milliseconds
jwt.refresh-token-expiration=604800000

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:demoproductdb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.ssl.enabled=true